#!/bin/bash

FORESTER_JAR="$HOME/local/bin/forester_1046.jar"


usage() {
  echo $(basename $0) "<greengenes_file> <tree_file> <output.phyloxml>"
}

if [ $1 = "-h" ] || [ $1 = "--help" ]; then
  usage
  exit 1
elif [ $1 = "--version" ]; then
  echo 0.1
  exit 1
elif [ $# -ne 3 ]; then
  usage
  exit 1
fi


grep -A 1 db_name $1 | paste - - - | sed -e 's/db_name=//' -e 's/organism=/TAXONOMY_SN:/' | cut -f 1,2 >$$.tmp.txt
java -cp "$FORESTER_JAR" org.forester.application.decorator -table $2 $$.tmp.txt $3

rm $$.tmp.txt
