#!/usr/bin/env ruby 

require 'bio'
require 'optparse'
require 'bio-logger'
require 'enumerator'

class App
  PROGRAM_NAME = "esomTools"
  
  attr_reader :options

  def initialize(arguments, stdin)
    @arguments = arguments
    @stdin = stdin
    
    # Set defaults
    @options = Hash.new
    @options[:verbose] = false
    @options[:quiet] = false
    # TO DO - add additional defaults
  end

  # Parse options, check arguments, then process the command
  def run
        
    if parsed_options?
      
      process_command
    end
      
  end
  
  protected
  
    def parsed_options?
      
      # Specify options
      opts = OptionParser.new
      opts.banner = "Usage: #{PROGRAM_NAME} [options]"
      opts.parse!(@arguments) rescue return false
      
      process_options
      unless arguments_valid?
        opts.help
      end
      true      
    end

    # Performs post-parse processing on options
    def process_options
      if @options.has_key?(:rm_class)
          @options[:rmcls] = true
      end
    end
    
    def output_options
      puts "Options:\
"
      
      @options.marshal_dump.each do |name, val|        
        puts "  #{name} = #{val}"
      end
    end

    # True if required arguments were provided
    def arguments_valid?
      return false if (@options[:partition_class] and @options[:rmcls])

      if @options[:rmcls]
        return false unless (@options[:cls_file] and @options[:lrn_file])
      elsif @options[:partition_class]
        return false unless (@options[:cls_file] and @options[:name_file] and @options[:fasta_file])
      end
      true
    end
    
    def process_command
    end


    def process_standard_input
      input = @stdin.read      
      # TO DO - process input
      
      # [Optional]
      # @stdin.each do |line| 
      #  # TO DO - process each line
      #end
    end

end #App

# not to be confused with Partition below
# this will simply remove the specified class
# from the lrn file
class RemoveCls

  def initialize(cls_file, lrn_file)
    @cls = cls_file
    @lrn = lrn_file
    # a lookup of the class(es) that we want to remove
    @classes = Hash.new
    # window to class hash map
    @windows = Hash.new
  end

  def populate_windows(line)
    a = line.split(/\t/)
    @windows[a[0]] = a[1]
    #@classes[a[1]] = true
  end

  def read_cls
    f = File.open(@cls)
    f.each do |line|
      line.chomp!
      next if line =~ /%/
      self.populate_windows(line)
    end
  end
  
  def read_lrn
    f = File.open(@lrn)
    f.each do |line|
      line.chomp!
      next if line =~ /%/
      l = line.split(/\t/)
      unless self.check_class(l[0])
        puts line
      end
    end
  end

  def check_class(window)
    @classes.has_key?(@windows[window])
  end

  def add_class(c)
    @classes[c] = true
  end

end #RemoveCls

# this class is designed to work with 
# the Partition class below.
# we store all of the windows for a contig as well as the 
# class that each window belonged to
class Contig
  include Enumerable
  attr_reader :name
  def initialize(name, log)
    @name = name
    @windows = Hash.new # elements are the window name and the class
    @@log = log
  end
  
  def each
    @windows.each{|k,v| yield k,v}
  end

  def []=(k,v)
    @windows[k] = v
  end

  def [](k)
    @windows[k]
  end

  # what percentage of the windows are covered by the 
  # most abundant class
  def mode_coverage(percent, zero_insignificant)

    coverage_hash = Hash.new(0)
    length = @windows.length
    @windows.each do |k,v| 
      if zero_insignificant & (v == '0')
        length -= 1
      end
      coverage_hash[v] += 1
    end
    max = 0
    max_class = nil
    coverage_hash.each do |k,v|
      if (v > max) 
        max = v 
        max_class = k
      end  
    end
    
    if max_class == '0'
    #  @@log.info self
      return max_class
    elsif max.to_f/length.to_f >= percent
    #  @@log.info self
      return max_class
    end
    #@@log.debug "#{max}/#{length}(orig: #{@windows.length}) < #{percent} (#{max.to_f/length.to_f})"
    @@log.warn "CANNOT RESOLVE BIN FOR: #{self}"
    return '666'
  end

  def to_s
    ret_str = "#{@name}\n"
    ret_str += "." * @windows.length
    ret_str += "\n"
    ret_str += "^" * @windows.length 
    ret_str += "\n"
    @windows.keys.sort.each{|i| ret_str += (@windows[i].length == 1)? @windows[i] : @windows[i].slice(0,1) }
    ret_str += "\n"
    @windows.keys.sort.each{|i| ret_str += (@windows[i].length == 2)? @windows[i].slice(1,1) : ' ' }
    ret_str += "\n"
    ret_str
  end

end # Contig

# given a ESOM .cls file and a fasta file
# partition all contigs from a class into a
# separate file
class Partition
  def initialize(cls_file, name_file, fasta_file, logger)
    @cls = cls_file
    @name = name_file
    @fasta = fasta_file
    @windows = Hash.new
    @contigs = Hash.new
    @classes = Hash.new{|h,k| h[k] = Array.new}
    @@log = logger
  end

  # the cls file contains lines of: window\tclass
  def populate_windows(line)
    a = line.split(/\t/)
    # this window is a member of this class
    @windows[a[0]] = a[1]
  end

  def read_cls
    f = File.open(@cls)
    f.each do |line|
      line.chomp!
      next if line =~ /%/
      self.populate_windows(line)
    end
  end
  
  # take a contig window name and 
  # convert it back to its original form
  def fix_contig_name(name)
    if nil != name.gsub!(/_leftover.*$/,'')
      return name
    elsif name =~ /(.*)_\d+$/
      return $1
    else 
      return name
    end
  end

  def read_names
    f = File.open(@name)
    contig_classes = Hash.new
    
    f.each do |line|
      line.chomp!
      next if line =~ /%/
      a = line.split(/\t/)
      
      if @windows.has_key?(a[0])
        name = self.fix_contig_name(a[1])
        #@contigs[name] = @windows[a[0]]
        
        if @contigs.has_key?(name)
          current_contig = @contigs[name]
          current_contig[a[1]] = @windows[a[0]]
        else
          # new contig, make a new object
          new_contig = Contig.new(name, @@log)
          new_contig[a[1]] = @windows[a[0]]
          @contigs[name] = new_contig #Contig.new(name) #@windows[a[0]]
        end
      end
    end
  end
  
  def print_contig
    @contigs.each do |k,v|
      puts v
    end
  end

  def partition_all_classes
    prefix = File.basename(@cls, ".cls")
    
    mapping = Hash.new
    @classes.each do |k,v|
      v.each{|contig| mapping[contig.name] = k}
    end

    ex = Extractor.new(mapping, false, prefix, "fa")
    ex.extract(@fasta)
  end

  def classify_contigs
    @contigs.each_value do |v|
      @classes[ v.mode_coverage(0.7, true) ] << v
    end
  end

  def partition
    self.read_cls
    self.read_names
    self.classify_contigs
    self.partition_all_classes
  end

end #Partition

class MergeCls
  def initialize(cls_file, class_list, outfile=nil)
    if not cls_file || cls_file == '-'
      @cls_file = $stdin
    else
      @cls_file = File.open(cls_file)
    end
    @classes = Hash.new
    class_list.sort!
    class_list.each{|i|@classes[i] = class_list[0]}
    if outfile
      @outfile = File.open(outfile,'w')
    else
      @outfile = $stdout
    end
  end
  def merge
    @cls_file.each do |line|
      line.chomp!
      if line =~ /%/
        @outfile.puts line 
      else
        name, cls = line.split(/\t/)
        if @classes.has_key?(cls)
          @outfile.puts "#{name}\t#{@classes[cls]}"
        else
          @outfile.puts line
        end
      end
    end
  end
end
# read a fasta file (or many) and extract reads
# that match a given list
class Extractor
  
  def initialize(mapping, invert, prefix, extension)
    @mapping = mapping
    @invert = invert
    @prefix = prefix
    @extension = extension
  end
  
  def make_file_name(unique)
    "#{@prefix}.#{unique}.#{@extension}"
  end

  def append_file(file,seq)
    out = File.open(file, 'a')
    out.puts seq
    out.close
  end

  def extract(infile)
    input_file = Bio::FlatFile.open(infile)
    input_file.each do |entry|
      if @mapping.has_key?(entry.definition)
        if not @invert
          self.append_file(self.make_file_name(@mapping[entry.definition]), entry)
        end
      elsif @invert
        self.append_file(self.make_file_name("NOCLASS"), entry)
      end
    end
  end

end #Extractor

if __FILE__ == $0 #needs to be removed if this script is distributed as part of a rubygem
  SCRIPT_NAME = File.basename(__FILE__); LOG_NAME = SCRIPT_NAME.gsub('.rb','')

  VERSION = "0.1.4"
  # Parse command line options into the options hash
  options = {
    :logger => 'stderr',
    :merge => nil
  }
  o = OptionParser.new do |opts|
    opts.banner = " Usage: #{SCRIPT_NAME} <arguments>\n Description of what this program does...\n\n"

    opts.on('-V', '--version', "Output version information")    { puts VERSION ; exit 0 }
    opts.on('-P', '--partition', "Given a particular class list, will segregate all contigs from a class into separate fasta files") {options[:partition_class] = true }
    opts.on('-R', '--remove', "Delete all the windows of a class from an lrn file") { options[:rmcls] = true }
    opts.on('-M', '--merge x,y,z', Array,
            "Merge multiple classes together. Give as an arguement the class numbers to be merged. The smallest class will be used in the output") do |list|
            options[:merge] = list
            end
    opts.on('--remove-class [INT]', "An integer value for the class that needs to be removed" ) {|v| options[:rm_class] = v}
    opts.on('-c', '--class-file FILE', "name of the class file") {|f| options[:cls_file] = f}
    opts.on('-f', '--fasta-file FILE', "name of the fasta file") {|f| options[:fasta_file] = f }
    opts.on('-n', '--name-file FILE', "name of the names file") {|f| options[:name_file] = f }
    opts.on('-l', '--lrn-file FILE', "name of the lrn file") {|f| options[:lrn_file] = f}
    opts.on('-v', '--inverse', "inverse the previous operations") { options[:inverse] = true }
    # logger options
    opts.on("-q", "--quiet", "Run quietly, set logging to ERROR level [default INFO]") {Bio::Log::CLI.trace('error')}
    opts.on("--logger filename",String,"Log to file [default #{options[:logger]}]") { |name| options[:logger] = name}
    opts.on("--trace options",String,"Set log level [default INFO]. e.g. '--trace debug' to set logging level to DEBUG"){|s| Bio::Log::CLI.trace(s)}
  end
  o.parse!
  if ARGV.length != 0
    $stderr.puts o
    exit 1
  end
  # Setup logging. bio-logger defaults to STDERR not STDOUT, I disagree
  Bio::Log::CLI.logger(options[:logger]); log = Bio::Log::LoggerPlus.new(LOG_NAME); Bio::Log::CLI.configure(LOG_NAME)


  if options[:partition_class]
    log.info "Partitioning classes"
    p = Partition.new(options[:cls_file], options[:name_file], options[:fasta_file], log)
    p.partition
  elsif options[:rmcls]
    r = RemoveCls.new(options[:cls_file], options[:lrn_file])
    r.add_class(options[:rm_class])
    r.read_cls
    r.read_lrn
  elsif options[:merge]
    m = MergeCls.new(options[:cls_file],options[:merge])
    m.merge
  end
  log.info "Done!"
end #end if running as a script
